import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  coinToConvertWithUsd: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    fontSize: 20,
    backgroundColor: 'rgba(200,200,200, 0.1)',
    textAlign: 'center',
    borderColor: '#DDDDDD',
    color: 'white',
    borderWidth: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  coinToConvertArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    fontSize: 20,
    backgroundColor: 'rgba(200,200,200, 0.2)',
    textAlign: 'center',
    borderColor: '#DDDDDD',
    color: 'white',
    borderWidth: 2,
    borderRadius: 10,
    overflow: 'hidden',
  },
  cryptoConverterSumText: {
    fontSize: 25,
    textAlign: 'right',
    color: 'white',
    flex: 1,
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    paddingLeft: 20,
    paddingRight: 20,
    height: 40,
    width: 10,
    marginTop: 25,
    marginBottom: 10
  },
  cryptoConverterHeadingText: {
    fontSize: 20,
    paddingBottom: 20,
    color: 'white',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cryptoConverterView: {
    flex: 1,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5'
  },
  imageBackgroundForConverter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    marginTop: 10,
    borderWidth: 5,
    borderColor: '#DDDDDD'
  },
  amountTextInput: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    height: 40,
    backgroundColor: 'rgba(200,200,200, 0.5)',
    borderColor: '#DDDDDD',
    color: 'white',
    borderWidth: 1,
    borderRadius: 20,
    padding: 10,
    marginLeft: 10,
    fontSize: 20,
    marginTop: 5
  },
})
